### ISSUE TITLE
Extra space before and after username

### ISSUE THREAD

**Issue by Eldenroot** [Sama34/OUGC-Thread-Contributors#1]
There is an extra space before and after username in list

**Comment by Eldenroot** [comment]
@Sama34 - same issue here, but fixed https://github.com/lukasamd/MyBB-Users-Browsed-Topic/commit/2d1ad497fbbf83b5a02ae658ebd7feb5ed554a22

**Comment by Sama34** [comment]
Thanks, I will check it later.

**Comment by Eldenroot** [comment]
@Sama34 - thank you, I really like this plugin. Quite useful! I am looking for a new release ;)
