### ISSUE TITLE
[Feature idea] Amount of posts per user

### ISSUE THREAD

**Issue by AlekzNet** [Sama34/OUGC-Thread-Contributors#6]
Just an idea: 
- add post counters to user names
- add a sort option "by post count" 

Thanks!

**Comment by AlekzNet** [comment]
Clarification: amount of posts in the current thread only.

**Comment by Sama34** [comment]
Please reply to this issue if you find any issue.

**Comment by AlekzNet** [comment]
Oh, I thought I replied - everything works perfectly! Thanks much!
